server:
  port: 8188 # å¯åŠ¨ç«¯å£
spring:
  datasource:
    db1: # æ•°æ®æº1
      jdbc-url: jdbc:mysql://localhost:3306/db1?characterEncoding=utf8&useUnicode=true&useSSL=false&serverTimezone=GMT%2B8
      username: root
      password: 123456
      driver-class-name: com.mysql.cj.jdbc.Driver
    db2: # æ•°æ®æº2
      jdbc-url: jdbc:mysql://localhost:3306/db2?characterEncoding=utf8&useUnicode=true&useSSL=false&serverTimezone=GMT%2B8
      username: root
      password: 123456
      driver-class-name: com.mysql.cj.jdbc.Driver

# ğŸ‘¼ğŸ‘¼ğŸ‘¼åœ¨æ¯ä¸€ä¸ªæ•°æ®æºçš„Configè®¾ç½®ä¹‹ä¸­, Mapperæ¥å£å’Œå¯¹åº”çš„Mapper.xmlå¿…é¡»è®¾ç½®å¥½ï¼Œå¦åˆ™å°±ä¼šåªæœ‰@Primaryçš„å¯ä»¥ä½¿ç”¨ç›¸æ¯”è¾ƒä¸‹æ¥ï¼Œ
# è¿˜æ˜¯ä½¿ç”¨mybatis-plus+dynamic-datasource-spring-boot-starterçš„æ–¹å¼æ›´åŠ æ–¹ä¾¿çµæ´»ï¼Œæ­¤ç§æ–¹å¼åªæ˜¯ä¸€ä¸ªé…ç½®å®éªŒã€‚

# è¿™ä¸ªå¯ä»¥å†™å¯ä»¥ä¸å†™, å†™çš„è¯ä¹Ÿè¡Œ, ä¸å†™çš„è¯ä¹Ÿè¡Œ, ä¸»è¦æœ€å¥½åœ¨dbconfigä¹‹ä¸­è®¾ç½®å¥½, å°±å¯ä»¥äº†
# mybatis:
#   mapper-locations: classpath:mapper/db1/*.xml,classpath*:mapper/db2/*.xml
# logé…ç½®
mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl